categories: Categories
search: Search...
searchFirst: First search, index file loading, please wait...
searchNoResult: No result
searchFilesNotfound: The search.xml file was not found, please refer to：
searchServiceErrors: The request failed, Try to refresh the page or try again later.
tags: Tags
frequent_tags: Frequently Used Tags
all_tags: All tags
filter_tags: Filter tags
no_tags_found: No tags found
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed
category: Category
tag: Tag
catalog: Contents
pinned: Pinned
updateTime: Update time
words: Words
about: About
friend: Friend
about_blog_stats: Blog statistics
about_posts: Posts
about_tags: Tags
about_categories: Categories
about_runtime_days: Runtime days
about_me: About me
about_tech_stack: Tech Stack
about_writing_activity: Writing Activity
about_year_posts: "%d: %d posts published"
about_activity_label: "Writing activity for the last %d days"
about_activity_day: "%s: %d posts"
about_less: Less
about_more: More
about_recent_posts: Recent Posts
